"""Stable public entry point for Keepygaga's core-memory API."""

from keepygaga.codec import (
    FACT_LINE_RE,
    FRONTMATTER_KEY_RE,
    MAX_FACT_CONTENT_CHARS,
    Basis,
    Fact,
    FactSelector,
    MemoryDocument,
    StoredFact,
    StrictModel,
    parse_memory_file,
    render_memory_file,
)
from keepygaga.errors import MemoryValidationError as MemoryValidationError
from keepygaga.memory_contract import (
    DEFAULT_DESCRIPTIONS,
    DYNAMIC_PAGE_LIMIT,
    DYNAMIC_PAGE_LIMITS,
    MAX_FACTS_PER_OPERATION,
    MAX_MUTATION_OPERATIONS,
    MAX_READ_PATHS,
    NEW_DIRECTORY_MODE,
    NEW_FILE_MODE,
    PREFERENCES_PAGE_LIMIT,
    PROFILE_PAGE_LIMIT,
    AddOperation,
    AddOperations,
    CreateOperation,
    CreateOperations,
    DeleteFactOperation,
    DeleteOperation,
    DeleteOperations,
    DeletePageOperation,
    MemoryScope,
    MoveOperation,
    MoveOperations,
    ReadPaths,
    RenameOperation,
    RenameOperations,
    RepairPageOperation,
    UpdateFactOperation,
    UpdateOperation,
    UpdateOperations,
    UpdatePageOperation,
    page_limit,
)
from keepygaga.memory_contract import (
    MAX_ALIASES_PER_PAGE as MAX_ALIASES_PER_PAGE,
)
from keepygaga.memory_contract import (
    MAX_DESCRIPTION_CHARS as MAX_DESCRIPTION_CHARS,
)
from keepygaga.memory_init import initialize_memory_tree
from keepygaga.memory_store import VERSION_RE, LoadedFile, MemoryStore
from keepygaga.paths import (
    DYNAMIC_DIRS,
    DYNAMIC_STEM_RE,
    FIXED_PATHS,
    canonical_memory_path,
    canonical_path,
    is_dynamic_path,
)

__all__ = [
    "AddOperation",
    "AddOperations",
    "Basis",
    "CreateOperation",
    "CreateOperations",
    "DEFAULT_DESCRIPTIONS",
    "DYNAMIC_DIRS",
    "DYNAMIC_STEM_RE",
    "DeleteFactOperation",
    "DeleteOperation",
    "DeleteOperations",
    "DeletePageOperation",
    "FACT_LINE_RE",
    "FIXED_PATHS",
    "FRONTMATTER_KEY_RE",
    "Fact",
    "FactSelector",
    "StoredFact",
    "LoadedFile",
    "DYNAMIC_PAGE_LIMIT",
    "DYNAMIC_PAGE_LIMITS",
    "MAX_FACTS_PER_OPERATION",
    "MAX_FACT_CONTENT_CHARS",
    "MAX_MUTATION_OPERATIONS",
    "MAX_READ_PATHS",
    "NEW_DIRECTORY_MODE",
    "NEW_FILE_MODE",
    "MemoryDocument",
    "MemoryScope",
    "MemoryStore",
    "MoveOperation",
    "MoveOperations",
    "PREFERENCES_PAGE_LIMIT",
    "PROFILE_PAGE_LIMIT",
    "ReadPaths",
    "RepairPageOperation",
    "RenameOperation",
    "RenameOperations",
    "StrictModel",
    "UpdateFactOperation",
    "UpdateOperation",
    "UpdateOperations",
    "UpdatePageOperation",
    "VERSION_RE",
    "canonical_memory_path",
    "canonical_path",
    "initialize_memory_tree",
    "is_dynamic_path",
    "parse_memory_file",
    "render_memory_file",
    "page_limit",
]
